### ISSUE TITLE
how can i start the program by systemd

### ISSUE THREAD

**Issue by cutemanworking** [fanpei91/gap-proxy#1]
THANKS FOR UR GREAT APP!!

i tried to start it by systemd, but got following err msg. what i missed?
/lib/systemd/system/gap-proxy.service:13: Invalid URL, ignoring: (8).  

config:
[Unit]
Description=gap-proxy  Default Server Service
After=network.target

[Service]
Type=simple
ExecStart=/usr/bin/gap-proxy server start

[Install]
WantedBy=multi-user.target

**Comment by fanpei91** [comment]
我对 systemd 不了解，爱莫能助。我好奇，gap-proxy 本身就能以 daemon 形式运行，为啥还要 systemd 呢？

**Comment by cutemanworking** [comment]
强迫症而已。 我用Daemon方式是可以的。 感谢回复！
